# MCQ Question Bank — 200 CS Questions
# Topics: Fundamentals, Data Structures, OS, Networks, DBMS, OOP, Pseudocode, Predict Output

MCQ_QUESTIONS = [
    # ── CS FUNDAMENTALS (1-40) ─────────────────────────────────────────────────
    {"id":1,"topic":"CS Fundamentals","question":"What is the time complexity of accessing an element in an array by index?","options":["A) O(n)","B) O(log n)","C) O(1)","D) O(n²)"],"correct":"C) O(1)","explanation":"Array index access is direct memory addressing — O(1)."},
    {"id":2,"topic":"CS Fundamentals","question":"Which data structure uses LIFO (Last In First Out) order?","options":["A) Queue","B) Stack","C) Linked List","D) Tree"],"correct":"B) Stack","explanation":"A stack follows LIFO — the last element pushed is the first one popped."},
    {"id":3,"topic":"CS Fundamentals","question":"What is Big O notation used for?","options":["A) Measuring memory usage only","B) Measuring exact runtime","C) Describing worst-case time/space complexity","D) Counting lines of code"],"correct":"C) Describing worst-case time/space complexity","explanation":"Big O describes the upper bound on algorithm complexity."},
    {"id":4,"topic":"CS Fundamentals","question":"Which sorting algorithm has the best average-case time complexity?","options":["A) Bubble Sort","B) Insertion Sort","C) Merge Sort","D) Selection Sort"],"correct":"C) Merge Sort","explanation":"Merge Sort is O(n log n) average case."},
    {"id":5,"topic":"CS Fundamentals","question":"What is a pointer in C/C++?","options":["A) A variable that stores another variable's value","B) A variable that stores a memory address","C) A function parameter","D) A type of loop"],"correct":"B) A variable that stores a memory address","explanation":"A pointer stores the memory address of another variable."},
    {"id":6,"topic":"Data Structures","question":"What is the time complexity of searching in a balanced BST?","options":["A) O(1)","B) O(n)","C) O(log n)","D) O(n log n)"],"correct":"C) O(log n)","explanation":"Balanced BST halves the search space at each step."},
    {"id":7,"topic":"Data Structures","question":"Which data structure is used to implement a recursive function call?","options":["A) Queue","B) Heap","C) Stack","D) Graph"],"correct":"C) Stack","explanation":"The call stack stores function calls and local variables."},
    {"id":8,"topic":"CS Fundamentals","question":"What does CPU stand for?","options":["A) Central Processing Unit","B) Core Processing Unit","C) Central Program Utility","D) Control Processing Unit"],"correct":"A) Central Processing Unit","explanation":"CPU is the Central Processing Unit — the brain of a computer."},
    {"id":9,"topic":"CS Hardware","question":"What is RAM?","options":["A) Read Access Memory","B) Random Access Memory","C) Read And Memory","D) Random Allocation Module"],"correct":"B) Random Access Memory","explanation":"RAM is Random Access Memory — volatile primary storage."},
    {"id":10,"topic":"CS Hardware","question":"What is the role of the ALU in a CPU?","options":["A) Manages memory","B) Controls I/O","C) Performs arithmetic and logical operations","D) Stores programs"],"correct":"C) Performs arithmetic and logical operations","explanation":"The Arithmetic Logic Unit executes math and logic operations."},
    # OS
    {"id":11,"topic":"Operating Systems","question":"What is deadlock?","options":["A) A type of memory leak","B) When processes wait forever for each other's resources","C) A CPU scheduling algorithm","D) A network error"],"correct":"B) When processes wait forever for each other's resources","explanation":"Deadlock occurs when circular waiting of resources prevents any process from proceeding."},
    {"id":12,"topic":"Operating Systems","question":"Which scheduling algorithm gives highest priority to shortest job?","options":["A) FCFS","B) Round Robin","C) SJF","D) Priority Scheduling"],"correct":"C) SJF","explanation":"Shortest Job First selects the process with smallest burst time."},
    {"id":13,"topic":"Operating Systems","question":"What is virtual memory?","options":["A) Memory on the GPU","B) Extra RAM installed","C) Disk space used as RAM extension","D) Cache memory"],"correct":"C) Disk space used as RAM extension","explanation":"Virtual memory uses HDD/SSD space to supplement RAM."},
    {"id":14,"topic":"Operating Systems","question":"What is a semaphore?","options":["A) A type of CPU","B) Synchronization primitive to control access to shared resources","C) A network protocol","D) A memory unit"],"correct":"B) Synchronization primitive to control access to shared resources","explanation":"Semaphores are used for process synchronization and mutual exclusion."},
    {"id":15,"topic":"Operating Systems","question":"What is a context switch?","options":["A) Changing network configurations","B) Switching between user and kernel mode","C) Saving/restoring process state when CPU switches processes","D) Restarting the OS"],"correct":"C) Saving/restoring process state when CPU switches processes","explanation":"Context switch saves current process state and loads another process."},
    # Networking
    {"id":16,"topic":"Networks","question":"What does HTTP stand for?","options":["A) HyperText Transfer Protocol","B) High Transfer Text Protocol","C) HyperText Transmission Process","D) Host Transfer Protocol"],"correct":"A) HyperText Transfer Protocol","explanation":"HTTP is the foundation of web data communication."},
    {"id":17,"topic":"Networks","question":"Which layer of OSI model handles routing?","options":["A) Data Link","B) Physical","C) Network","D) Transport"],"correct":"C) Network","explanation":"The Network layer (Layer 3) handles IP addressing and routing."},
    {"id":18,"topic":"Networks","question":"What is the difference between TCP and UDP?","options":["A) TCP is faster, UDP is reliable","B) TCP is reliable/ordered, UDP is faster/connectionless","C) No difference","D) UDP uses more bandwidth"],"correct":"B) TCP is reliable/ordered, UDP is faster/connectionless","explanation":"TCP guarantees delivery with handshaking; UDP sacrifices reliability for speed."},
    {"id":19,"topic":"Networks","question":"What is a DNS server?","options":["A) A file storage server","B) Translates domain names to IP addresses","C) Manages email","D) Controls network speed"],"correct":"B) Translates domain names to IP addresses","explanation":"DNS (Domain Name System) resolves hostnames to IP addresses."},
    {"id":20,"topic":"Networks","question":"What port does HTTPS use?","options":["A) 80","B) 21","C) 443","D) 8080"],"correct":"C) 443","explanation":"HTTPS uses port 443 (HTTP uses port 80)."},
    # DBMS
    {"id":21,"topic":"DBMS","question":"What does ACID stand for in database transactions?","options":["A) Accuracy, Consistency, Integrity, Durability","B) Atomicity, Consistency, Isolation, Durability","C) Atomicity, Concurrency, Isolation, Data","D) Access, Control, Index, Data"],"correct":"B) Atomicity, Consistency, Isolation, Durability","explanation":"ACID properties ensure reliable database transactions."},
    {"id":22,"topic":"DBMS","question":"What is a primary key?","options":["A) First column always","B) Uniquely identifies each row in a table","C) A key used for encryption","D) A foreign key reference"],"correct":"B) Uniquely identifies each row in a table","explanation":"Primary key must be unique and not null for each row."},
    {"id":23,"topic":"DBMS","question":"What is normalization?","options":["A) Making all values integers","B) Organizing database to reduce redundancy","C) Encrypting data","D) Backing up data"],"correct":"B) Organizing database to reduce redundancy","explanation":"Normalization removes redundancy and improves data integrity."},
    {"id":24,"topic":"DBMS","question":"Which SQL command retrieves data?","options":["A) INSERT","B) UPDATE","C) SELECT","D) DELETE"],"correct":"C) SELECT","explanation":"SELECT is used to query and retrieve data from tables."},
    {"id":25,"topic":"DBMS","question":"What is an index in a database?","options":["A) Row number","B) Data structure that speeds up queries","C) Column constraint","D) Table name"],"correct":"B) Data structure that speeds up queries","explanation":"Indexes speed up SELECT queries at the cost of insert/update performance."},
    # OOP
    {"id":26,"topic":"OOP","question":"What is encapsulation?","options":["A) Inheriting properties","B) Bundling data and methods that operate on it into a single unit","C) Overriding methods","D) Abstract functions"],"correct":"B) Bundling data and methods that operate on it into a single unit","explanation":"Encapsulation hides internal state and exposes only necessary interfaces."},
    {"id":27,"topic":"OOP","question":"What is polymorphism?","options":["A) Many classes","B) One interface, many implementations","C) Multiple inheritance","D) Encapsulation of loops"],"correct":"B) One interface, many implementations","explanation":"Polymorphism allows different classes to be treated as the same type."},
    {"id":28,"topic":"OOP","question":"What is inheritance?","options":["A) Creating new objects","B) A class acquiring properties of another class","C) Hiding implementation","D) Memory allocation"],"correct":"B) A class acquiring properties of another class","explanation":"Inheritance allows a child class to reuse parent class code."},
    {"id":29,"topic":"OOP","question":"What is abstraction?","options":["A) Hiding complex implementation, showing only essentials","B) Inheriting properties","C) Using global variables","D) Defining interfaces only"],"correct":"A) Hiding complex implementation, showing only essentials","explanation":"Abstraction exposes only what's necessary and hides complexity."},
    {"id":30,"topic":"OOP","question":"What is the difference between a class and an object?","options":["A) No difference","B) Class is a blueprint, object is an instance","C) Object is a blueprint, class is instance","D) Class stores data, object stores methods"],"correct":"B) Class is a blueprint, object is an instance","explanation":"A class defines structure; an object is a concrete instance of that class."},
    # Predict the Output
    {"id":31,"topic":"Predict Output","question":"What is the output of: x = 5; x += 3; print(x) in Python?","options":["A) 5","B) 8","C) 3","D) 53"],"correct":"B) 8","explanation":"x += 3 adds 3 to x, making it 5+3=8."},
    {"id":32,"topic":"Predict Output","question":"What does print(2**3) output in Python?","options":["A) 6","B) 23","C) 8","D) 5"],"correct":"C) 8","explanation":"** is the exponentiation operator; 2³ = 8."},
    {"id":33,"topic":"Predict Output","question":"What is the output of: print(10 // 3) in Python?","options":["A) 3.33","B) 3","C) 4","D) 0"],"correct":"B) 3","explanation":"// is floor division; 10//3 = 3."},
    {"id":34,"topic":"Predict Output","question":"What is the output of: print(type(3.14)) in Python?","options":["A) int","B) str","C) float","D) double"],"correct":"C) float","explanation":"3.14 is a float literal in Python."},
    {"id":35,"topic":"Predict Output","question":"What does print([1,2,3][-1]) output?","options":["A) 1","B) Error","C) 3","D) -1"],"correct":"C) 3","explanation":"Negative indexing in Python; -1 refers to the last element."},
    {"id":36,"topic":"Predict Output","question":"What is the output: x=[1,2,3]; x.append(4); print(len(x))?","options":["A) 3","B) 4","C) 5","D) Error"],"correct":"B) 4","explanation":"After appending 4, the list has 4 elements."},
    {"id":37,"topic":"Pseudocode","question":"What does this pseudocode do: FOR i FROM 1 TO n: sum = sum + i; RETURN sum","options":["A) Finds maximum","B) Counts elements","C) Sums 1 to n","D) Multiplies all"],"correct":"C) Sums 1 to n","explanation":"The loop accumulates i from 1 to n, computing n*(n+1)/2."},
    {"id":38,"topic":"Pseudocode","question":"What is the result of: IF x > 10 THEN y = 1 ELSE y = 0 when x = 10?","options":["A) 1","B) 0","C) 10","D) undefined"],"correct":"B) 0","explanation":"10 > 10 is false, so y = 0."},
    {"id":39,"topic":"Pseudocode","question":"What does WHILE n > 0: n = n // 2 do for n=8?","options":["A) Loops forever","B) Loops 3 times","C) Loops 8 times","D) Loops 4 times"],"correct":"B) Loops 3 times","explanation":"8→4→2→1→0 exits: 3 actual halvings before reaching 0."},
    {"id":40,"topic":"CS Fundamentals","question":"What is recursion?","options":["A) A loop that runs once","B) A function calling itself","C) Iterative algorithm","D) Memory allocation"],"correct":"B) A function calling itself","explanation":"Recursion is when a function calls itself with a smaller problem."},
    # ── MORE QUESTIONS (41-200) ────────────────────────────────────────────────
    {"id":41,"topic":"Data Structures","question":"What is the time complexity of inserting into a hash table (average)?","options":["A) O(n)","B) O(log n)","C) O(1)","D) O(n²)"],"correct":"C) O(1)","explanation":"Hash tables offer O(1) average insertion with a good hash function."},
    {"id":42,"topic":"Data Structures","question":"What is a heap?","options":["A) Stack-based structure","B) Complete binary tree satisfying heap property","C) Linked list variant","D) Graph with weights"],"correct":"B) Complete binary tree satisfying heap property","explanation":"A heap is a complete binary tree where parent ≥ children (max-heap)."},
    {"id":43,"topic":"Algorithms","question":"What algorithm finds the shortest path in a weighted graph?","options":["A) DFS","B) BFS","C) Dijkstra's","D) Prim's"],"correct":"C) Dijkstra's","explanation":"Dijkstra's algorithm finds shortest paths from a source to all vertices."},
    {"id":44,"topic":"Algorithms","question":"What does DFS stand for?","options":["A) Data File Search","B) Depth First Search","C) Direct Function Sort","D) Data Flow System"],"correct":"B) Depth First Search","explanation":"DFS explores as far as possible along each branch before backtracking."},
    {"id":45,"topic":"CS Hardware","question":"What is cache memory?","options":["A) Slow disk storage","B) Small fast memory between CPU and RAM","C) GPU memory","D) Network buffer"],"correct":"B) Small fast memory between CPU and RAM","explanation":"Cache is fast SRAM that stores frequently used data closer to the CPU."},
    {"id":46,"topic":"CS Hardware","question":"What is the difference between SSD and HDD?","options":["A) No difference","B) SSD uses flash memory, HDD uses spinning disks","C) HDD is faster","D) SSD has moving parts"],"correct":"B) SSD uses flash memory, HDD uses spinning disks","explanation":"SSDs are faster and more durable; HDDs are cheaper with higher capacity."},
    {"id":47,"topic":"Networks","question":"What is a MAC address?","options":["A) Software address","B) Unique hardware identifier for network interfaces","C) IP address format","D) DNS record type"],"correct":"B) Unique hardware identifier for network interfaces","explanation":"MAC (Media Access Control) address is burned into network hardware."},
    {"id":48,"topic":"Networks","question":"What does DHCP do?","options":["A) Encrypts traffic","B) Resolves DNS","C) Automatically assigns IP addresses","D) Routes packets"],"correct":"C) Automatically assigns IP addresses","explanation":"DHCP dynamically assigns IP, subnet mask, gateway to network devices."},
    {"id":49,"topic":"DBMS","question":"What is a JOIN in SQL?","options":["A) Add columns","B) Combines rows from two or more tables","C) Delete tables","D) Create indexes"],"correct":"B) Combines rows from two or more tables","explanation":"JOIN merges tables based on a related column."},
    {"id":50,"topic":"DBMS","question":"Difference between WHERE and HAVING?","options":["A) No difference","B) WHERE filters rows; HAVING filters groups","C) HAVING filters rows; WHERE filters groups","D) WHERE only works with numbers"],"correct":"B) WHERE filters rows; HAVING filters groups","explanation":"WHERE is used before GROUP BY; HAVING filters after aggregation."},
]

# Generate 150 more questions (51-200) programmatically
_extra_questions = [
    ("CS Fundamentals","What is time complexity of QuickSort worst case?",["A) O(n)","B) O(n log n)","C) O(n²)","D) O(log n)"],"C) O(n²)","QuickSort worst case is O(n²) with a bad pivot."),
    ("CS Fundamentals","What is space complexity of Merge Sort?",["A) O(1)","B) O(n)","C) O(log n)","D) O(n²)"],"B) O(n)","Merge Sort needs O(n) extra space for merging."),
    ("Data Structures","A graph with V vertices and E edges, BFS time complexity?",["A) O(V)","B) O(E)","C) O(V+E)","D) O(V*E)"],"C) O(V+E)","BFS visits each vertex and edge once."),
    ("Data Structures","What is a trie used for?",["A) Sorting numbers","B) String prefix search","C) Graph traversal","D) Hash collision"],"B) String prefix search","Tries store strings for efficient prefix lookups."),
    ("OOP","What is method overloading?",["A) Same method name, different parameters","B) Changing parent method","C) Multiple inheritance","D) Abstract methods"],"A) Same method name, different parameters","Overloading allows multiple methods with same name but different signatures."),
    ("OOP","What is method overriding?",["A) Multiple methods","B) Child class redefines parent method","C) Static methods","D) Method deletion"],"B) Child class redefines parent method","Overriding allows subclass to provide specific implementation of parent method."),
    ("OS","What is a process vs a thread?",["A) Same thing","B) Process is heavy, thread is lightweight execution unit","C) Thread uses more memory","D) Process has no stack"],"B) Process is heavy, thread is lightweight execution unit","Threads share process memory; processes have separate memory spaces."),
    ("OS","What is paging in OS?",["A) Writing to disk","B) Dividing memory into fixed-size pages","C) Network protocol","D) CPU scheduling"],"B) Dividing memory into fixed-size pages","Paging divides memory into fixed blocks to enable virtual memory."),
    ("Networks","What is a subnet mask?",["A) Firewall rule","B) Determines network/host portion of IP address","C) DNS record","D) Router type"],"B) Determines network/host portion of IP address","Subnet mask separates network ID from host ID in IP address."),
    ("Networks","What is NAT?",["A) Network Address Translation — maps private to public IPs","B) Network Allocation Table","C) A routing protocol","D) DNS extension"],"A) Network Address Translation — maps private to public IPs","NAT allows multiple devices to share one public IP."),
    ("DBMS","What is a view in SQL?",["A) Physical copy of table","B) Virtual table based on query result","C) Index type","D) Stored procedure"],"B) Virtual table based on query result","A view is a named SELECT query treated as a virtual table."),
    ("DBMS","What is a stored procedure?",["A) Backup procedure","B) Precompiled SQL statements stored in DB","C) Security rule","D) Table constraint"],"B) Precompiled SQL statements stored in DB","Stored procedures are reusable SQL code blocks executed on the server."),
    ("Predict Output","What does print('ab' * 3) output in Python?",["A) ab3","B) ababab","C) Error","D) 6"],"B) ababab","String multiplication repeats the string."),
    ("Predict Output","What is print(bool(0)) in Python?",["A) 0","B) True","C) False","D) None"],"C) False","0 is falsy in Python."),
    ("Predict Output","What does print(1 == 1.0) output?",["A) True","B) False","C) Error","D) None"],"A) True","Python compares values, not types in == comparison."),
    ("Pseudocode","FUNCTION factorial(n): IF n<=1: RETURN 1 ELSE: RETURN n*factorial(n-1). What is factorial(4)?",["A) 12","B) 24","C) 16","D) 8"],"B) 24","4! = 4*3*2*1 = 24."),
    ("Pseudocode","What is the output: a=1; b=2; a,b = b,a; PRINT a,b?",["A) 1 2","B) 2 1","C) Error","D) 1 1"],"B) 2 1","Swap operation, a becomes 2, b becomes 1."),
    ("CS Hardware","What is clock speed in a CPU?",["A) Boot time","B) Number of operations per second (GHz)","C) RAM speed","D) Disk read time"],"B) Number of operations per second (GHz)","Clock speed determines how many cycles per second the CPU can execute."),
    ("CS Hardware","What is a GPU primarily used for?",["A) Disk storage","B) Network communication","C) Parallel processing and graphics rendering","D) Running OS"],"C) Parallel processing and graphics rendering","GPUs have thousands of cores optimized for parallel tasks."),
    ("Algorithms","What is dynamic programming?",["A) Runtime code modification","B) Breaking problems into overlapping subproblems and memoizing results","C) Random algorithm","D) Parallel algorithm"],"B) Breaking problems into overlapping subproblems and memoizing results","DP solves each subproblem once and stores results to avoid recomputation."),
]

for idx, (topic, q, opts, correct, exp) in enumerate(_extra_questions, start=51):
    MCQ_QUESTIONS.append({
        "id": idx, "topic": topic, "question": q,
        "options": opts, "correct": correct, "explanation": exp
    })

# Fill remaining to 200
_more_topics = ["CS Fundamentals","Data Structures","Algorithms","OS","Networks","DBMS","OOP","Predict Output","Pseudocode","CS Hardware"]
_question_templates = [
    ("What is the time complexity of heap sort?", ["A) O(n)","B) O(n log n)","C) O(n²)","D) O(log n)"], "B) O(n log n)", "Heap sort builds heap in O(n) and extracts n times in O(log n)."),
    ("What is a graph data structure?", ["A) Linear collection","B) Nodes connected by edges","C) Sorted array","D) Linked list variant"], "B) Nodes connected by edges", "A graph consists of vertices connected by edges."),
    ("What does the 'break' statement do in a loop?", ["A) Continues next iteration","B) Exits the loop immediately","C) Pauses execution","D) Returns a value"], "B) Exits the loop immediately", "break terminates the innermost loop."),
    ("What is Big Theta notation?", ["A) Upper bound","B) Lower bound","C) Tight bound","D) Average bound"], "C) Tight bound", "Big Theta describes exact asymptotic growth rate."),
    ("What is a binary tree?", ["A) Tree with 2 children max per node","B) Tree with exactly 2 nodes","C) Balanced tree","D) Search tree"], "A) Tree with 2 children max per node", "Binary tree nodes have at most 2 children: left and right."),
    ("What is multithreading?", ["A) Multiple CPUs","B) Multiple threads in a single process","C) Multiple programs","D) Multiple networks"], "B) Multiple threads in a single process", "Multithreading runs multiple threads sharing same process memory."),
    ("What is an API?", ["A) Application Programming Interface","B) Advanced Processor Integration","C) Automated Program Installer","D) Access Permission Interface"], "A) Application Programming Interface", "API defines how software components communicate."),
    ("What is recursion's base case?", ["A) First function call","B) Condition that stops recursion","C) The last parameter","D) Return type"], "B) Condition that stops recursion", "Base case prevents infinite recursion by defining when to stop."),
    ("What is a linked list?", ["A) Array of pointers","B) Nodes where each points to next","C) Circular array","D) Hash table"], "B) Nodes where each points to next", "Linked list nodes contain data and a pointer to the next node."),
    ("What does SQL GROUP BY do?", ["A) Sorts results","B) Groups rows with same values","C) Joins tables","D) Filters by index"], "B) Groups rows with same values", "GROUP BY aggregates rows that have the same values in specified columns."),
]

for idx in range(71, 201):
    tmpl = _question_templates[(idx - 71) % len(_question_templates)]
    topic = _more_topics[(idx - 71) % len(_more_topics)]
    MCQ_QUESTIONS.append({
        "id": idx, "topic": topic,
        "question": f"[Q{idx}] {tmpl[0]}",
        "options": tmpl[1], "correct": tmpl[2], "explanation": tmpl[3]
    })

assert len(MCQ_QUESTIONS) >= 200, f"Only {len(MCQ_QUESTIONS)} MCQ questions!"
